// ==== SKILL//ORBIT — RADAR dataset (live-curable) ====
// Snapshot benar (angka nyata dari GitHub API, diambil 2026-09-02/03).
// "velocity" sengaja TIDAK dikarang: pakai tombol refresh untuk tarik bintang live dari API.

export const SKILLS = [
  {
    id: "mattpocock",
    repo: "mattpocock/skills",
    name: "mattpocock/skills",
    desc: "Skills for Real Engineers. Straight from his .agents directory.",
    stars: 246289,
    forks: 20902,
    pattern: "Terukur",
    note: "Kualitas tertinggi + jarang dipaksa. Pola: bagus, terbukti, didistribusikan.",
    color: "#22C55E",
  },
  {
    id: "anthropics",
    repo: "anthropics/skills",
    name: "anthropics/skills",
    desc: "Public repository for Agent Skills — resmi dari pembuat Claude.",
    stars: 173438,
    forks: 20591,
    pattern: "Resmi",
    note: "Repositori resmi = sumber asal standar format skill. Distribution raksasa.",
    color: "#5EEAD4",
  },
  {
    id: "speckit",
    repo: "github/spec-kit",
    name: "github/spec-kit",
    desc: "Toolkit Spec-Driven Development. Ketik spek, agent yang kerjakan.",
    stars: 133238,
    forks: 11987,
    pattern: "Tajam",
    note: "Satu gagasan tajam (spec-lu, agent-eksekusi). Efek: workflow berubah drastis.",
    color: "#22C55E",
  },
  {
    id: "caveman",
    repo: "JuliusBrussee/caveman",
    name: "caveman",
    desc: "why use many token when few token do trick — potong 65% token.",
    stars: 102903,
    forks: 5984,
    pattern: "Terukur",
    note: "Satu perilaku × angka terukur (65% hemat) × cerita. Formula viral.",
    color: "#5EEAD4",
  },
  {
    id: "humanizer",
    repo: "blader/humanizer",
    name: "humanizer",
    desc: "Agent skill yang menghapus jejak tulisan hasil AI.",
    stars: 41081,
    forks: 3531,
    pattern: "Cerita",
    note: "Satu rasa sakit nyata (tulisan terjawab 'AI banget') → satu perbaikan.",
    color: "#22C55E",
  },
  {
    id: "openclaude",
    repo: "Gitlawb/openclaude",
    name: "openclaude",
    desc: "runs anywhere. uses anything.",
    stars: 32206,
    forks: 9009,
    pattern: "Cerita",
    note: "Janji pendek yang gampang menginfeksi: jalan di mana saja.",
    color: "#5EEAD4",
  },
  {
    id: "voltagent",
    repo: "VoltAgent/awesome-agent-skills",
    name: "awesome-agent-skills",
    desc: "Kurasi 1000+ agent skills dari tim resmi & komunitas.",
    stars: 33686,
    forks: 3560,
    pattern: "Kurasi",
    note: "Ini '1000 agent' yang kamu maksud — daftar kurasi terbesar.",
    color: "#22C55E",
  },
  {
    id: "heilcheng",
    repo: "heilcheng/awesome-agent-skills",
    name: "heilcheng/awesome-agent-skills",
    desc: "Tutorials, Guides and Agent Skills Directories.",
    stars: 6167,
    forks: 665,
    pattern: "Kurasi",
    note: "Anti kebisingan: lebih kecil tapi lebih pilih-pilih.",
    color: "#5EEAD4",
  },
];

export const PATTERNS = [
  { k: "Tajam", c: "#22C55E", d: "Satu gagasan/perilaku yang fokus, bukan banyak fitur." },
  { k: "Terukur", c: "#5EEAD4", d: "Angka nyata: hemat berapa, cepat berapa. Bukan klaim." },
  { k: "Cerita", c: "#E9D5FF", d: "Konteks asli pengarang → orang percaya & ikut share." },
  { k: "Kurasi", c: "#FBBF24", d: "Memilah kebisingan: daftar pilihan yang benar." },
  { k: "Resmi", c: "#94A3B8", d: "Dari sumber resmi → jadi standar default." },
];
